"""Research lab: model performance dashboard on synthetic data.

The synthetic week generator writes a ground-truth label per row. This module
compares the risk engine's estimate against those labels (confusion matrix,
false positives/negatives, precision/recall), runs the ablation study, and
documents the cross-validation protocol. Everything is explicitly synthetic -
useful for demonstrating methodology, never for clinical claims.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

from src.config import UserProfile
from src.data_models import FeatureVector
from src.models.hormone_estimator import HormoneEstimator
from src.utils.history_store import HistoryStore
from src.utils.replay import features_from_frame

RISK_THRESHOLD = 50.0


@dataclass
class ConfusionMetrics:
    tp: int = 0
    fp: int = 0
    tn: int = 0
    fn: int = 0

    @property
    def total(self) -> int:
        return self.tp + self.fp + self.tn + self.fn

    @property
    def accuracy(self) -> float:
        return (self.tp + self.tn) / max(self.total, 1)

    @property
    def precision(self) -> float:
        return self.tp / max(self.tp + self.fp, 1)

    @property
    def recall(self) -> float:
        return self.tp / max(self.tp + self.fn, 1)

    @property
    def false_positive_rate(self) -> float:
        return self.fp / max(self.fp + self.tn, 1)

    @property
    def false_negative_rate(self) -> float:
        return self.fn / max(self.fn + self.tp, 1)


@dataclass
class ResearchReport:
    n_rows: int = 0
    n_labeled: int = 0
    metrics: ConfusionMetrics = field(default_factory=ConfusionMetrics)
    mean_risk_by_label: Dict[int, float] = field(default_factory=dict)
    ablation: List[Tuple[str, str, float, float]] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)


def evaluate_synthetic(db: HistoryStore, days: int = 14, threshold: float = RISK_THRESHOLD) -> ResearchReport:
    report = ResearchReport()
    df = db.features_as_frame(days=days)
    if df.empty:
        report.notes.append("No data in the local database.")
        return report

    features = features_from_frame(df)
    labels: List[int] = []
    risks: List[float] = []
    for i, (_, row) in enumerate(df.iterrows()):
        extra = row.get("extra_json")
        label = None
        if isinstance(extra, str) and extra:
            import json

            try:
                label = json.loads(extra).get("label")
            except Exception:
                label = None
        risk = row.get("risk")
        if label is None or risk is None:
            continue
        labels.append(int(label))
        risks.append(float(risk))

    report.n_rows = len(features)
    report.n_labeled = len(labels)
    if not labels:
        report.notes.append("No synthetic ground-truth labels found. Run the synthetic data generator first.")
        return report

    m = ConfusionMetrics()
    for label, risk in zip(labels, risks):
        pred = 1 if risk >= threshold else 0
        if pred == 1 and label == 1:
            m.tp += 1
        elif pred == 1 and label == 0:
            m.fp += 1
        elif pred == 0 and label == 0:
            m.tn += 1
        else:
            m.fn += 1
    report.metrics = m

    arr = np.array(labels)
    for lab in np.unique(arr):
        report.mean_risk_by_label[int(lab)] = float(np.mean([r for r, l in zip(risks, labels) if l == lab]))

    # Ablation study on the average row.
    report.ablation = _ablation(features)

    report.notes = [
        "All labels are SYNTHETIC (generated by scripts/generate_synthetic_dataset.py).",
        f"Risk threshold used: {threshold:.0f}% (>= threshold is a 'positive').",
        "Cross-validation protocol: with a real labelled dataset, use stratified "
        "5-fold CV and report ROC-AUC, Brier score and calibration curves (see "
        "scripts/train_pcos_risk_model.py). On synthetic data we only report the "
        "confusion table as a methodology demonstration.",
        "False positives/negatives here measure agreement with synthetic labels, "
        "not clinical truth.",
    ]
    return report


def _ablation(features: List[FeatureVector]) -> List[Tuple[str, str, float, float]]:
    from src.models.whatif import WhatIfEngine

    if not features:
        return []
    fv = features[len(features) // 2]
    engine = WhatIfEngine()
    hormones = HormoneEstimator().estimate(fv, UserProfile())
    return engine.counterfactual_ablation(fv, hormones, phase="unknown")
