"""Typed data containers used across the CHRONO-PCOS application."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


@dataclass
class SensorSample:
    """One decoded Arduino sample.

    `timestamp_s` is generated by Python wall-clock time. `ms` is Arduino millis.
    """

    timestamp_s: float
    ms: int
    ir: int
    red: int
    ax_g: float
    ay_g: float
    az_g: float
    gx_dps: float
    gy_dps: float
    gz_dps: float
    temp_c: float
    gsr_raw: int
    lux: float
    ecg_raw: int = -1
    mic_raw: int = -1
    mic_rms: float = 0.0
    mic_pitch_hz: float = 0.0
    fsr_raw: int = -1
    temp1_c: float = float('nan')
    room_temp_c: float = float('nan')
    humidity_pct: float = float('nan')
    pressure_hpa: float = float('nan')
    buttons: int = 0
    status: int = 0
    ppg_quality: float = 1.0
    source: str = "serial"  # serial or demo


@dataclass
class FeatureVector:
    """Real-time physiological features, mostly 0-100 normalized domain scores."""

    timestamp_s: float = 0.0
    hr_bpm: Optional[float] = None
    spo2_pct: Optional[float] = None
    rmssd_ms: Optional[float] = None
    sdnn_ms: Optional[float] = None
    pnn50_pct: Optional[float] = None
    ppg_pulse_amplitude: Optional[float] = None
    lux: Optional[float] = None
    fsr_raw: Optional[float] = None
    ecg_raw: Optional[float] = None
    ecg_hr_bpm: Optional[float] = None
    ecg_rmssd_ms: Optional[float] = None
    ecg_quality: float = 0.0
    mic_rms: Optional[float] = None
    mic_pitch_hz: Optional[float] = None
    voice_vasc_score: float = 0.0
    room_temp_c: Optional[float] = None
    humidity_pct: Optional[float] = None
    pressure_hpa: Optional[float] = None
    mv_challenge_risk: float = 0.0
    motion_index: float = 0.0
    activity_level: float = 0.0
    skin_temp_c: Optional[float] = None
    temp_slope_c_per_min: float = 0.0
    gsr_tonic: Optional[float] = None
    gsr_phasic_per_min: float = 0.0
    stress_index: float = 0.0
    acute_stress: float = 0.0
    chronic_stress: float = 0.0
    autonomic_imbalance: float = 0.0
    sleep_status: str = "unknown"
    sleep_probability: float = 0.0
    deep_sleep_probability: float = 0.0
    rem_probability: float = 0.0
    glucose_risk: float = 0.0
    bp_risk: float = 0.0
    systolic_bp: Optional[float] = None
    diastolic_bp: Optional[float] = None
    insulin_resistance_probability: float = 0.0
    metabolic_syndrome_proxy: float = 0.0
    inflammation_score: float = 0.0
    circadian_stability_index: float = 50.0
    circadian_disruption: float = 50.0
    low_activity_risk: float = 0.0
    temperature_rhythm_disruption: float = 50.0
    signal_quality: float = 0.0
    baseline_completeness: float = 0.0
    # Personalization / baseline.
    baseline_available: bool = False
    baseline_age_s: Optional[float] = None
    hr_zscore: Optional[float] = None
    rmssd_zscore: Optional[float] = None
    skin_temp_zscore: Optional[float] = None
    gsr_zscore: Optional[float] = None
    # FSR pressure correction.
    fsr_pressure_index: Optional[float] = None
    ppg_pulse_amplitude_corrected: Optional[float] = None
    # Anomaly detection.
    anomaly_score: float = 0.0
    anomalies: List[str] = field(default_factory=list)

    def as_dict(self) -> Dict[str, float | str | None]:
        return self.__dict__.copy()


@dataclass
class HormoneEstimate:
    name: str
    value: float
    unit: str
    ci_low: float
    ci_high: float
    confidence: float
    drivers: List[str] = field(default_factory=list)
    note: str = "Estimated Hormone Level - not measured"


@dataclass
class RiskResult:
    risk_percent: float
    ci_low: float
    ci_high: float
    confidence: float
    category: str
    domain_scores: Dict[str, float]
    contributions: List[Tuple[str, float, str]]
    explanation: str
    hormone_estimates: Dict[str, HormoneEstimate] = field(default_factory=dict)


@dataclass
class SleepMetrics:
    sleep_duration_min: float = 0.0
    time_in_bed_min: float = 0.0
    sleep_efficiency_pct: float = 0.0
    wake_frequency: int = 0
    restlessness_pct: float = 0.0
    deep_sleep_estimate_pct: float = 0.0
    rem_probability_pct: float = 0.0
    sleep_consistency_pct: float = 0.0
    circadian_disruption_pct: float = 50.0


@dataclass
class CircadianMetrics:
    stability_index: float = 50.0
    disruption_score: float = 50.0
    hr_r2: float = 0.0
    hrv_r2: float = 0.0
    temp_r2: float = 0.0
    gsr_r2: float = 0.0
    activity_regular: float = 0.0
    sleep_regular: float = 0.0
    light_regular: float = 0.0
    sleep_midpoint_sd_h: Optional[float] = None
